[project]
name = "llm-router-service"
version = "0.1.0"
description = "Asynchronous LLM router with councils and selectors"
authors = [{name = "Unknown"}]
dependencies = [
    "tiktoken",
    "textstat",
    "promptlayer",
    "litellm",
    "python-dotenv",
    "langchain-ollama",
    "requests",
    "pydantic",
    "tqdm",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

